# Generated by Django 4.1.7 on 2023-04-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
    ]
