# Generated by Django 4.1.7 on 2023-04-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_feedback_course_remove_feedback_lesson_and_more'),
        ('users', '0004_customuser_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='courses',
        ),
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(to='lessons.lesson'),
        ),
    ]
