# Generated by Django 4.1.7 on 2023-04-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_feedback_course_remove_feedback_lesson_and_more'),
        ('users', '0005_remove_customuser_courses_customuser_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(to='lessons.course'),
        ),
    ]
