# Generated by Django 4.1.7 on 2023-04-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='course',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='progress',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
